# Generated by Django 6.0.6 on 2026-06-19 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_remove_auctionlist_image_url_alter_auctionlist_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlist',
            name='category',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='item',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='item',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
